import re

new_descriptions = {
    'La Catedral y La Rapadura': 'El verdadero protagonista de este punto es su geología volcánica. Durante el recorrido, los contraluces creados por los haces de luz filtrándose a través de las grietas del techo de la cueva ofrecen estampas fotográficas inigualables. La inmersión de La Catedral es una de las experiencias de buceo más espectaculares y majestuosas de Tenerife. Se trata de una impresionante estructura de origen volcánico cuyas descomunales bóvedas, arcos y pasadizos naturales emulan la arquitectura de un templo gótico sumergido.',
    'Baja del Realejo': 'Este pico rocoso basáltico que se levanta desde los 60 metros de profundidad, y sube casi perpendicularmente formando varios escalones hasta los -9 metros, se encuentra rodeado de grandes piedras que forman pasillos y cuevas donde habitan gran cantidad de especies.<br><br><strong>Aguas limpias y cristalinas, un increíble paisaje.</strong><br>Hay que tener en cuenta las condiciones del mar en la zona ya que condicionan la inmersión, sin embargo, si vamos con buena mar, esta es una de las inmersiones donde podemos observar gran cantidad y variedad de fauna. La baja sirve de refugio a muchos peces pequeños como las bogas o las sardinas. Además, también podremos nadar entre morenas, abades, meros, bicudas, burritos listados, etc',
    'Tubo de Garachico': '<strong>El llamado Tubo de Garachico es una de las cuevas más profundas que podremos encontrar en todo el archipiélago.</strong> Un túnel de más de 150 m con claraboyas que cuenta con tubos volcánicos con accesibilidad para el buceo deportivo.<br><br><strong>Largo y estrecho tubo volcánico.</strong><br>Pese a su longitud el túnel no cuenta con ramificaciones por lo que no podremos perdernos. En el recorrido bucearemos junto pequeños invertebrados. A medida que avancemos el paisaje se convertirá en todo un espectáculo y podremos nadar entre fulas blancas, catalufas, chuchos negros, o cigalas canarias.',
    'Acantilado de Los Gigantes': 'La inmersión de La Atlántida, frente a los acantilados de Los Gigantes, es una de las más singulares y misteriosas de Tenerife. Su nombre hace honor al espectacular paisaje submarino formado por una serie de columnas basálticas hexagonales, similares a las de la Calzada del Gigante en Irlanda, que crean la sensación de estar explorando una ciudad sumergida de origen ancestral. Esta formación geológica única se encuentra entre los 18 y 30 metros de profundidad, lo que la hace accesible para buceadores con experiencia. Además del impresionante relieve, la zona alberga una interesante vida marina: abades, meros, viejas, morenas y bancos de roncadores son habituales, y no es raro ver rayas o incluso tiburones ángel en determinadas épocas. Las aguas claras y la atmósfera casi irreal de La Atlántida la convierten en una inmersión imprescindible para quienes buscan belleza natural, historia geológica y emociones bajo el mar.',
    'Cueva de los Cerebros': '<strong>Una de las cuevas más grandes de Canarias</strong><br>Esta cueva formada por tubos volcánicos fue declarada como ZEC (Zona Especial de Conservación), ya que se trata de un ecosistema único y muy vulnerable. Pese a ser una de las cuevas más grandes del archipiélago, el lecho del túnel está cubierto por pequeños cayados, lo que la hace segura para su exploración.<br><br><strong>Nadar entre una fauna peculiar</strong><br>El nombre a esta inmersión se debe a la presencia de unas peculiares esponjas en forma de cerebros que habitan sus aguas, y que están incluídas en el Catálogo de Especies Amenazadas de Canarias. Lo más destacable de esta cueva es su fauna con especies que generalmente viven en la penumbra como las anémonas, la cigala canaria, los chuchos negros, las langostas canarias, las catalufas, etc',
    'El Balito': 'Espectaculares formaciones rocosas, túneles y cuevas te sorprenderán en este sitio de buceo. A lo largo de las dos diferentes inmersiones que se pueden realizar, podrás ver anemonas gigantes, langostas, diferentes tipos de rayas y un sinfín de vida marina. Pensarás de estar en otro planeta al adentrarte en sus cuevas con tragaluces repletas de vida marina.',
    'El Bufadero': '<strong>Apta para todos los niveles</strong><br>Esta bella inmersión, apta para todos los niveles, cuenta con profundidades que van desde los 8 hasta los 25 metros de profundidad. Es una inmersión sencilla pero apasionante y llena de vida, que consta de tres niveles para un descenso controlado. Se recomienda evitar entrar a la cueva ya que puede ser peligroso.<br><br><strong>Gran concentración de fauna</strong><br>Podremos nadar entre peces trompetas, gallitos y pejeverdes desde los primeros metros, incluso es posible avistar tortugas verdes. A medida que descendamos, podremos encontrar miles de rocas que son el hogar de decenas de anémonas, pulpos, erizos diademos, cigalas, etc. En la cota más profunda, sus claras aguas nos permitirán ver el arenal en donde las anguilas jardineras son las protagonistas junto con obispos, chuchos, ratones y mantelinas.',
    'Cueva de las Morenas': 'Palm Mar Cave (La Cueva de las Morenas) es una inmersión avanzada en cueva frente a Palm-Mar en el sur de Tenerife, alcanzando 32 metros de profundidad. Este impresionante sistema de cavernas volcánicas debe su nombre a las numerosas morenas que habitan sus oscuras cámaras, con morenas mediterráneas y negras enroscadas en las grietas. La cueva presenta múltiples entradas y una gran cámara principal donde la luz filtrada crea efectos azules atmosféricos. Las paredes están cubiertas de esponjas y organismos incrustantes, mientras camarones y crustáceos se mueven en las zonas más oscuras. Fuera de la cueva, el arrecife alberga meros, barracudas y tortugas marinas. La significativa profundidad combinada con el entorno de techo exige conciencia avanzada de buceo en cuevas.',
    'Pecio El Condesito': '<strong>Sumergirse en un cañón submarino con pecio</strong><br>El barco de 30 metros de eslora ‘El Condesito’ encalló frente a la costa del extremo sur de la isla de Tenerife en 1971. El desafortunado accidente dejó dos legados importantes: el faro de Rasca, que se construyó para evitar que se repitiera el infortunio, y el pecio de ‘El Condesito’, uno de los puntos de buceo más singulares de Tenerife. El pecio, fragmentado en varios trozos, está en el fondo de un cañón submarino de 20 metros de profundidad flanqueado por paredes con forma prismática y frecuentado por abundante vida marina.<br><br><strong>Inmersión en fondo submarino de rocas prismáticas</strong><br>El punto de fondeo de la embarcación se encuentra a 3,7 millas náuticas del puerto del gran núcleo turístico de Los Cristianos, en una punta en la que las corrientes pueden aumentar la dificultad de la inmersión a nivel medio. El lugar está cerca de la costa y es hogar de numerosos pulpos, chocos y viejas. La inmersión suele incluir un paseo por las vecinas y espectaculares rocas con forma de prisma, que parecen invitar al buzo a subir sus escalones a pie. Su escasa profundidad y su buena visibilidad lo convierten en un buen pecio para practicar snorkel.',
    'Faro de Punta Rasca': '<strong>Inmersión en órganos submarinos en el sur de Tenerife</strong><br>Uno de los paisajes volcánicos más interesantes de Tenerife está bajo el mar, frente al faro de Rasca, en el punto más meridional de la isla. Bajo las cristalinas aguas del Atlántico discurre una serie de barrancos submarinos creados hace miles de años por lenguas de lava. Al enfriarse, esta lava dio lugar a estructuras tan caprichosas como las escaleras de peldaños prismáticos, también conocidos en las Islas Canarias como ‘órganos’. El faro también es un punto caliente de vida marina que hará las delicias de buceadores algo experimentados y fotógrafos submarinos.<br><br><strong>Nadar entre bancos de roncadores cerca de Las Galletas</strong><br>Al sitio se llega en menos de 10 minutos en embarcación desde el vecino puerto de Las Galletas. La inmersión suele incluir un descenso de ocho metros en vertical hasta los órganos y un recorrido hasta la cota 20 metros entre barrancos, arcos de piedra y túneles. Densos cardúmenes de roncadores de color amarillo y plata planean sobre los pequeños arenales, y se pueden llegar a ver angelotes y verrugatos semiescondidos. Sobre el azul, patrullan cardúmenes de bicudas formando círculos . Y sobre la roca, preciosas anémonas dejan mecer sus finos tentáculos.',
    'Bahía de Abades': 'Destino ideal para los amantes del buceo y el snorkel. Con aguas cristalinas, una rica biodiversidad marina y condiciones perfectas para principiantes de certificación Open Water como para niveles más avanzados como Advanced, o incluso Divemaster. Este lugar se ha convertido en un paraíso para los buceadores. Si estás buscando una experiencia inolvidable bajo el agua, Abades es el lugar ideal.<br><br><strong>¿Por qué elegir Abades para bucear?</strong><br><strong>Aguas tranquilas y cristalinas:</strong> Las aguas alrededor de Abades ofrecen una visibilidad excelente, a menudo superando los 20 metros, lo que permite disfrutar plenamente de la belleza submarina.<br><br><strong>Biodiversidad marina única:</strong> En estas aguas encontrarás una gran variedad de vida marina, como rayas, sepias, pulpos, peces trompeta y hasta tortugas. Además, las formaciones volcánicas submarinas crean un paisaje espectacular.<br><br><strong>Ideal para principiantes y expertos:</strong> Abades cuenta con puntos de inmersión adaptados a todos los niveles. Desde aguas poco profundas perfectas para aprender, hasta rutas más desafiantes para buceadores avanzados. Salidas de snorkel, cursos de Open Water, Advanced Open Water, Rescue Diver e incluso para el desarrollo del programa de Divemaster.<br><br><strong>Fácil acceso y ambiente acogedor:</strong> La playa de Abades está a pocos pasos del pueblo, lo que facilita el acceso a las zonas de buceo. Además, el lugar cuenta con una atmósfera tranquila y varios centros de buceo.',
    'Las Eras': '<strong>Inmersión llena de vida y belleza</strong><br>Las Eras es una de las inmersionas más conocidas de Tenerife. En ella encontraremos una gran variedad de especies e incluso estatuas. Su estrecho pasadizo, y su conjunto de formaciones rocosas, combinado con la luz que atraviesa las grietas, hacen de su paisaje uno de los más bellos para fotografiar.<br><br><strong>Refugio y hogar de multitud de especies marinas</strong><br>La inmersión consta de una gran pared de roca volcánica que va desde los 9 metros de profundidad hasta aproximadamente los 18 metros. Entre las pequeñas grietas, cuevas y pasadizos se esconden muchas especies como el chucho negro, morenas, pulpos, barracudas, meros, peces trompetas, rayas, etc.',
    'Punta Prieta': 'El punto fuerte de este recorrido es su impresionante relieve submarino de origen volcánico donde confluyen las siguientes características clave:<br><strong>Profundidad:</strong> Promedio de 20 metros y máxima de 38 metros.<br><strong>Fauna destacada:</strong> Caballitos de mar, meros, rayas, morenas picopato, angelotes y grandes bancos de roncadores.',
    'Boca Cangrejo': 'Bocacangrejo es una inmersión de orilla apta para principiantes en la costa este de Tenerife, alcanzando 18 metros de profundidad. Nombrado por la ensenada rocosa que sirve como punto de entrada, este sitio presenta un arrecife volcánico accesible con interesantes formaciones rocosas, pequeñas cuevas y parches de arena. La caleta protegida proporciona fácil entrada al agua y condiciones tranquilas, haciéndolo popular para inmersiones de formación. Peces trompeta, sepias y lábridos adornados son avistamientos comunes, mientras las grietas rocosas albergan cangrejos (haciendo honor al nombre), nudibranquios y pequeñas morenas. La exposición de la costa este asegura condiciones de buceo fiables.',
    'Añaza': 'El buceo en Añaza es una popular inmersión de costa situada en Santa Cruz de Tenerife. Ofrece una entrada fácil por la rampa del embarcadero y es accesible para todos los niveles. Podrás explorar hermosos arrecifes volcánicos, fondos arenosos y un veril profundo rebosante de vida marina.'
}

with open('index.html', 'r', encoding='utf-8') as f:
    content = f.read()

for site_name, new_desc in new_descriptions.items():
    escaped_site = re.escape(site_name)
    # The pattern matches: .bindPopup(px('Name', 'depth', 'level', 'type', ...
    # And everything until the final ));
    pattern = r"(\.bindPopup\(px\('" + escaped_site + r"',\s*'[^']*',\s*'[^']*',\s*'[^']*',\s*)[\s\S]*?(\s*\)\);)"
    
    safe_desc = new_desc.replace("'", "\\'")
    
    def repl(m):
        return m.group(1) + "'" + safe_desc + "'" + m.group(2)
        
    content = re.sub(pattern, repl, content)

with open('index.html', 'w', encoding='utf-8') as f:
    f.write(content)

print('Descriptions updated successfully.')
